# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '07-GesturesAndCoco' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "FlexColorPicker"
  target '07-GesturesAndCocoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '07-GesturesAndCocoUITests' do
    # Pods for testing
  end

end
